const FEED_PATH = '/home'
const LOGIN_PATH = '/login'
const REGISTER_PATH = '/register'
const PROFILE_PATH = '/myprofile'
const USER_PROFILE_PATH = "/profile/:slug"
const PROFILE_ACTIVITY_PATH = 'activity'
const PROFILE_ABOUT_PATH = 'about'
const PROFILE_FRIENDS_PATH = 'friends'
const PROFILE_PHOTOS_PATH = 'photos'
const PROFILE_VIDEOS_PATH = 'videos'
const SEARCH_RESULTS_PATH = 'search-results'
const SEARCH_RESULTS_ALL_PATH = 'all'
const SEARCH_RESULTS_PEOPLE_PATH = 'people'
const SEARCH_RESULTS_POSTS_PATH = 'posts'
const SEARCH_RESULTS_CHARITIES_PATH = 'charities'
const SEARCH_RESULTS_SPONSORS_PATH = 'sponsors'

const paths = {
  FEED_PATH,
  LOGIN_PATH,
  REGISTER_PATH,
  PROFILE_PATH,
  USER_PROFILE_PATH,
  PROFILE_ACTIVITY_PATH,
  PROFILE_ABOUT_PATH,
  PROFILE_FRIENDS_PATH,
  PROFILE_PHOTOS_PATH,
  PROFILE_VIDEOS_PATH,
  SEARCH_RESULTS_PATH,
  SEARCH_RESULTS_ALL_PATH,
  SEARCH_RESULTS_PEOPLE_PATH,
  SEARCH_RESULTS_POSTS_PATH,
  SEARCH_RESULTS_CHARITIES_PATH,
  SEARCH_RESULTS_SPONSORS_PATH
} as const

export default paths
